<a href="https://colab.research.google.com/github/a3539a/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/07/05
이름 : 김승용
내용 : 파이썬 Numpy 패키지 실습하기
"""
import numpy as np

In [ ]:
# numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
print('v1 :',v1)

v2 = np.arange(5)
print('v2 :',v2)

v3 = np.arange(10)
print('v3 :',v3)

v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이의 임의의 실수
rand1 = np.random.rand(100)
print(rand1)

# 표준 정규 분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)

# 0 ~ 9 사이의 임의의 정수
rand3 = np.random.randint(10)
print(rand3)

[0.02940859 0.35402163 0.4135438  0.28323427 0.34992725 0.31210053
 0.58397647 0.45286153 0.70102584 0.20231325 0.06516513 0.57521968
 0.14276449 0.31810656 0.11598892 0.81517646 0.13831245 0.62505116
 0.90812879 0.74964547 0.17757045 0.18926408 0.35826708 0.71645542
 0.04908625 0.82297927 0.92745392 0.69001358 0.59400984 0.24476707
 0.87267298 0.97694127 0.52217115 0.26060301 0.56255486 0.68532137
 0.80482129 0.73135967 0.53797775 0.48891975 0.82718274 0.6279342
 0.3118081  0.13966485 0.90938608 0.80296106 0.04884538 0.07606833
 0.80028594 0.13286202 0.79632785 0.12367727 0.61621471 0.38016187
 0.87159089 0.08674144 0.42315251 0.98589828 0.83455406 0.64334698
 0.030392   0.0524787  0.59765681 0.78970764 0.2877221  0.16372299
 0.56435882 0.99339859 0.40529065 0.23450106 0.55010415 0.9684377
 0.40496467 0.67219319 0.9091969  0.50380086 0.98031231 0.5890634
 0.37898009 0.15569144 0.4529713  0.25277161 0.45715009 0.45924887
 0.39251313 0.14783431 0.34763569 0.12031447 0.98117445 0.6331771

In [ ]:
# numpy 자료구조 - 행렬
m1 = np.array([[1,2], [3,4]])
print(m1)

m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m2)

m3 = np.ones([2,14])
print(m3)

m4 = np.zeros([3,12])
print(m4)


[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 전치행렬
print(m1.T)

print(m2.transpose())

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 단위행렬
e1 = np.identity(5)
print(e1)

e2 = np.identity(6)
print(e2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# 역행렬
im1 = np.linalg.inv(m1)
print(im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# 행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)

print(matrix[0,0])
print(matrix[0,:])
print(matrix[:,0])

print(matrix[0:2, 0:2])
print(matrix[:, 0:2])
print(matrix[:, 2:4])
print(matrix[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
